### ISSUE TITLE
Error when trying to install .appx file.

### ISSUE THREAD

**Issue by twerking** [ambiennt/MCBEx86#1]
So i installed the 1.18.12 86x Minecraft version and as i click "Reinstall" it shows this error, same thing goes when i delete minecraft and i have to "Install" it , it keeps showing the same.
![Screenshot_39](https://github.com/ambiennt/MCBEx86/assets/92944539/2e3aace2-467d-4b69-8fe8-951e8ccfb70e)

**Comment by ambiennt** [comment]
The issue you are showing is not relevant to this repository. All appx files in the releases tab are signed by Microsoft and have not been tampered with. Can you install any other appx (such as from a different version or architecture, i.e. 64 bit?)

**Comment by IgnBatt** [comment]
I was having the same issue, installing the package through powershell worked.
https://www.youtube.com/watch?v=03F9sOJSn8k
