### ISSUE TITLE
Please make 1.18.2 xbox patch.

### ISSUE THREAD

**Issue by xDqrK4O4** [ambiennt/MCBEx86#2]
Hi , Ambiennt. Love your contribution to the hive community. The 1.18.12 xbox live patch is outstanding!. However , Its request that can you patch the 1.18.2 also? . 1.18.2 Is surprisingly Much Smoother than 1.18.12.

Thank you.

**Comment by ambiennt** [comment]
Please take a look at https://github.com/ambiennt/KeyPatcher
