### ISSUE TITLE
XBL authentication broken

### ISSUE THREAD

**Issue by sdw4938** [ambiennt/MCBEx86#4]
It appears the Xbox Live authentication is broken again for the 1.18.12 XBL authentication patch. I tried to connect to servers that support 1.18, but I kept getting connection failed errors. I also tried to connect to a LAN 1.18.12 server in online mode, but the game threw up an authentication error.

I'm wondering if Microsoft changed its key again.

**Comment by ambiennt** [comment]
I can't find any information which suggests that Microsoft has changed its public authentication key in recent releases. It still appears to be the one used by my [KeyPatcher](https://github.com/ambiennt/KeyPatcher/blob/efe7cd105892f995391acabb47abd37c5a0fa918/KeyPatcher/src/main.cpp#L8C10-L8C170) tool, which has also been applied to the [1.18.12 XBL authentication patch](https://github.com/ambiennt/MCBEx86/releases/tag/1.18.12-xbox-auth-patch) release in this repository. This is most likely an issue with RakNet/the protocol of whatever server you're trying to join.

**Comment by ambiennt** [comment]
> I also tried to connect to a LAN 1.18.12 server in online mode, but the game threw up an authentication error.

You need to apply my KeyPatcher tool to the server executable (assuming you're talking about the 1.18.12 BDS).
